### ISSUE TITLE
error when running or building test files.

### ISSUE THREAD

**Issue by Haroenv** [bodil/pink#1]
```
pink build slides.js 
ERROR: Module build failed: TypeError: Cannot read property 'forEach' of undefined
    at Object.module.exports (/usr/local/lib/node_modules/pink/es6-loader.js:25:13)
net.js:633
    throw new TypeError('invalid data');
          ^
TypeError: invalid data
    at WriteStream.Socket.write (net.js:633:11)
    at WriteStream.stream.write (/usr/local/lib/node_modules/pink/node_modules/ansi/lib/newlines.js:36:21)
    at Cursor.write (/usr/local/lib/node_modules/pink/node_modules/ansi/lib/ansi.js:157:23)
    at /usr/local/lib/node_modules/pink/bin/pink.js:115:10
    at Tapable.<anonymous> (/usr/local/lib/node_modules/pink/node_modules/webpack/lib/Compiler.js:150:20)
    at Tapable.<anonymous> (/usr/local/lib/node_modules/pink/node_modules/webpack/lib/Compiler.js:349:18)
    at /usr/local/lib/node_modules/pink/node_modules/webpack/node_modules/tapable/lib/Tapable.js:99:11
    at Tapable.<anonymous> (/usr/local/lib/node_modules/pink/node_modules/webpack/lib/Compilation.js:341:18)
    at Tapable.<anonymous> (/usr/local/lib/node_modules/pink/node_modules/webpack/lib/Compilation.js:326:20)
    at /usr/local/lib/node_modules/pink/node_modules/webpack/lib/Compilation.js:258:11
```

```
pink run slides.js 
Development server running: http://localhost:1337

/usr/local/lib/node_modules/pink/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/middleware.js:85
            if(err) throw err;
                          ^
ModuleBuildError: Module build failed: TypeError: Cannot read property 'forEach' of undefined
    at Object.module.exports (/usr/local/lib/node_modules/pink/es6-loader.js:25:13)
    at DependenciesBlock.onModuleBuildFailed (/usr/local/lib/node_modules/pink/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:286:19)
    at nextLoader (/usr/local/lib/node_modules/pink/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:247:31)
    at /usr/local/lib/node_modules/pink/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:268:15
    at runSyncOrAsync (/usr/local/lib/node_modules/pink/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:171:4)
    at nextLoader (/usr/local/lib/node_modules/pink/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:266:3)
    at Storage.finished (/usr/local/lib/node_modules/pink/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at fs.js:334:14
    at /usr/local/lib/node_modules/pink/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:104:5
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by Haroenv** [comment]
probably not relevant anymore
