### ISSUE TITLE
pink run fails with Error: Cannot find module 'ansi'

### ISSUE THREAD

**Issue by meonkeys** [bodil/pink#19]
I'm using node v8.6.0 and npm v5.3.0 (installed via `nvm`, in case that matters). I was trying to get pink running so I could view https://github.com/bodil/are-we-there-yet locally. `npm install -g pink` worked, but `pink run` (or `pink` anything, it seems) fails with:

```
module.js:529
    throw err;
    ^

Error: Cannot find module 'ansi'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/adamm/.nvm/versions/node/v8.6.0/lib/node_modules/pink/bin/pink.js:11:12)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by meonkeys** [comment]
This might be why: https://github.com/bodil/pink/commit/3bc073fb4be182d69520d721c5b88e5f2e3623b5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L22
